#!/bin/bash

WALLPAPER_DIR="$HOME/Pictures/wallpapers"

if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "Error: Wallpaper directory $WALLPAPER_DIR does not exist!"
    exit 1
fi

NAMES=$(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) -printf "%f\n" | sort)

SELECTED_NAME=$(echo "$NAMES" | yad --list \
    --title="Wallpaper Selector" \
    --column="Wallpaper Name" \
    --width=400 --height=600 \
    --center \
    --no-markup \
    --search-column=1)

SELECTED_NAME=${SELECTED_NAME%\|}         # Remove trailing pipe if any
SELECTED_NAME=$(echo "$SELECTED_NAME" | xargs)  # Trim whitespace/newlines

if [ -n "$SELECTED_NAME" ]; then
    SELECTED_PATH="$WALLPAPER_DIR/$SELECTED_NAME"
    if [ -f "$SELECTED_PATH" ]; then
        gsettings set org.gnome.desktop.background picture-uri-dark "file://$SELECTED_PATH"
        gsettings set org.gnome.desktop.background picture-uri "file://$SELECTED_PATH"
    else
        echo "Error: File not found: $SELECTED_PATH"
    fi
fi
